name: Deploy React App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 'develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies and build React app
        run: |
          npm install
          npm run build

      - name: Build Docker image
        run: docker build -t react-app .

      - name: Save Docker image to file
        run: docker save react-app > react-app.tar

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "react-app.tar"
          target: "~/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < ~/react-app.tar
            docker stop react-app || true
            docker rm react-app || true
            docker run -d --name react-app -p 80:80 react-app